export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR'

export const FETCH_FOLLOWER_REQUEST = 'FETCH_FOLLOWER_REQUEST'
export const FETCH_FOLLOWER_SUCCESS = 'FETCH_FOLLOWER_SUCCESS'
export const FETCH_FOLLOWER_ERROR = 'FETCH_FOLLOWER_ERROR'

export const FETCH_REPO_REQUEST = 'FETCH_REPO_REQUEST'
export const FETCH_REPO_SUCCESS = 'FETCH_REPO_SUCCESS'
export const FETCH_REPO_ERROR = 'FETCH_REPO_ERROR'
